
export const HOTEL_CURRENCIES = [
    { code: "USD", label: "US Dollar (USD)" },
    { code: "EUR", label: "Euro (EUR)" },
    { code: "GBP", label: "British Pound (GBP)" },
    { code: "AED", label: "UAE Dirham (AED)" },
    { code: "INR", label: "Indian Rupee (INR)" },
    { code: "CAD", label: "Canadian Dollar (CAD)" },
    { code: "AUD", label: "Australian Dollar (AUD)" },
    { code: "JPY", label: "Japanese Yen (JPY)" },
    { code: "CNY", label: "Chinese Yuan (CNY)" },
    { code: "CHF", label: "Swiss Franc (CHF)" },
    { code: "SAR", label: "Saudi Riyal (SAR)" },
    { code: "ZAR", label: "South African Rand (ZAR)" },
    { code: "BRL", label: "Brazilian Real (BRL)" },
    { code: "MXN", label: "Mexican Peso (MXN)" },
    { code: "SGD", label: "Singapore Dollar (SGD)" },
    { code: "HKD", label: "Hong Kong Dollar (HKD)" },
    { code: "KRW", label: "South Korean Won (KRW)" },
    { code: "TRY", label: "Turkish Lira (TRY)" },
    { code: "THB", label: "Thai Baht (THB)" },
    { code: "PLN", label: "Polish Zloty (PLN)" },
    { code: "SEK", label: "Swedish Krona (SEK)" },
    { code: "NOK", label: "Norwegian Krone (NOK)" },
    { code: "DKK", label: "Danish Krone (DKK)" },
    { code: "CZK", label: "Czech Koruna (CZK)" },
    { code: "HUF", label: "Hungarian Forint (HUF)" },
    { code: "RON", label: "Romanian Leu (RON)" },
    { code: "RUB", label: "Russian Ruble (RUB)" },
    { code: "UAH", label: "Ukrainian Hryvnia (UAH)" },
    { code: "EGP", label: "Egyptian Pound (EGP)" },
    { code: "ILS", label: "Israeli Shekel (ILS)" },
    { code: "QAR", label: "Qatari Riyal (QAR)" },
    { code: "KWD", label: "Kuwaiti Dinar (KWD)" },
    { code: "BHD", label: "Bahraini Dinar (BHD)" },
    { code: "OMR", label: "Omani Rial (OMR)" },
    { code: "JOD", label: "Jordanian Dinar (JOD)" },
    { code: "MYR", label: "Malaysian Ringgit (MYR)" },
    { code: "IDR", label: "Indonesian Rupiah (IDR)" },
    { code: "ARS", label: "Argentine Peso (ARS)" },
    { code: "CLP", label: "Chilean Peso (CLP)" },
    { code: "COP", label: "Colombian Peso (COP)" },
    { code: "NZD", label: "New Zealand Dollar (NZD)" },
    { code: "TWD", label: "Taiwan Dollar (TWD)" },
    { code: "VND", label: "Vietnamese Dong (VND)" },
    { code: "AZN", label: "Azerbaijani Manat (AZN)" },
    { code: "BGN", label: "Bulgarian Lev (BGN)" },
    { code: "FJD", label: "Fijian Dollar (FJD)" },
    { code: "GEL", label: "Georgian Lari (GEL)" },
    { code: "KZT", label: "Kazakhstani Tenge (KZT)" },
    { code: "MDL", label: "Moldovan Leu (MDL)" },
    { code: "NAD", label: "Namibian Dollar (NAD)" },
    { code: "XOF", label: "West African CFA Franc (XOF)" },
] as const;

export type HotelCurrencyCode = (typeof HOTEL_CURRENCIES)[number]["code"];

const CURRENCY_SYMBOLS: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    NGN: "₦",
    INR: "₹",
    JPY: "¥",
    CNY: "¥",
    KRW: "₩",
    AED: "د.إ",
    SAR: "﷼",
    ZAR: "R",
    BRL: "R$",
    MXN: "$",
    CAD: "$",
    AUD: "$",
    NZD: "$",
    SGD: "$",
    HKD: "$",
    TWD: "NT$",
    THB: "฿",
    TRY: "₺",
    RUB: "₽",
    PLN: "zł",
    CHF: "CHF",
};

export function getCurrencySymbol(code?: string) {
    if (!code) return "";
    return CURRENCY_SYMBOLS[code] || code;
}
